---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  MYSQL_IP_ADDRESS: 10.129.0.32
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: kube-java
          image: cr.yandex/crpeha3ouabjt9dl7vkb/kube-java:latest
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: my-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-app
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec: 
  rules:
  - host: ot-us.ddns.net
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
        path: /
